// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmiwlygkJn0bYVe8HAqn_2gSeLPE2UboY',
    appId: '1:1029906964489:web:ef41931158bb8e5f3798d8',
    messagingSenderId: '1029906964489',
    projectId: 'rim-stor',
    authDomain: 'rim-stor.firebaseapp.com',
    storageBucket: 'rim-stor.firebasestorage.app',
    measurementId: 'G-KS4T85T4MY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq_VcKvsi0YwT9acjulogvLXa-T-UskRU',
    appId: '1:1029906964489:android:084a6a6cf2af944b3798d8',
    messagingSenderId: '1029906964489',
    projectId: 'rim-stor',
    storageBucket: 'rim-stor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfR_w-T-f4cZDIR15H4M3niGRcnWoJPso',
    appId: '1:1029906964489:ios:758bb69cb5922a693798d8',
    messagingSenderId: '1029906964489',
    projectId: 'rim-stor',
    storageBucket: 'rim-stor.firebasestorage.app',
    iosBundleId: 'com.example.rimStor',
  );
}
